server:
  port: 8010
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    root: info
    com.ll.exam.app_2022_12_12__1: debug